#pragma	once

#include <stdint.h>

#define OPTIMIZATION 0
#define FIRST_ISA 1
#define OLD 0
#define OLD_STRICT 1
enum opcode : uint8_t {
  HALT, 
  ADD, SUB, SUBI, ADDI, 
  FADD, FADDA, FADDN, FSUB, FSUBA, FSUBN, 
  FMUL, FMULA, FMULN, FINV, FINVA, FINVN, 
  FABS, FNEG, SQRT, SQRTA, SQRTN, 
  AND, OR, NOR, XOR, ANDI, ORI, 
  SLL, SRL, SRA,
  R2R, F2F, R2F, F2R, ITOF, FTOI, FLOOR,
  LUI, LLI, FLUI, FLLI, 
  LW, LWI, FLW, FLWA, FLWN, FLWI, FLWIA, FLWIN, 
  SW, SWI, FSW, FSWI, 
  IN, FIN, 
  OUTA, OUTB, OUTC, OUTD, FOUTA, FOUTB, FOUTC, FOUTD, 
  J, JL, JR, JLR, 
  BEQ, BEQI, FBEQ, BNE, BNEI, FBNE, 
  BLTE, BLTEI, FBLTE, BGTE, BGTEI, FBGTE, 
  BEQR, BEQIR, FBEQR, BNER, BNEIR, FBNER, 
  BLTER, BLTEIR, FBLTER, BGTER, BGTEIR, FBGTER, 
  NOP, DBG
#if OLD
  ,FINDF1, SLLR, SRLR
#endif
#if FIRST_ISA
  ,CMP, CMPF, DIVF
#endif
  , UNKNOWN// 末尾から動かすな
};

const int OPCNUM = UNKNOWN;
